#!/bin/bash

mkdir /tmp/setup
cd /tmp/setup

wget https://gist.githubusercontent.com/shawnbon206/f7327c3f9d0d1a246a2f/raw/13065c0aefe38f7f78c3b6612e859c7587a3e52c/sources.list --quiet
mv /etc/apt/sources.list /tmp/setup/sources.bak
cat /tmp/setup/sources.list >> /etc/apt/sources.list

apt-get update
apt-get -y dist-upgrade
apt-get -y upgrade

wget https://raw.githubusercontent.com/Cynesiz/linux-configs/master/home/.bashrc --quiet

rm -rf /etc/bash.bashrc
mv /tmp/setup/.bashrc /etc/bash.bashrc
rm -rf ~/.bashrc
source /etc/bash.bashrc

wget -O /tmp/setup/stupid https://raw.githubusercontent.com/Cynesiz/linux-configs/master/sledge-hammer-to-kill-a-fly/%20stupid-locales-problem.sh --quiet

chmod +x /tmp/setup/stupid
cd /tmp/setup
./stuipd

apt-get -y install git udhcpc sudo nano links iptraf htop dnsutils whois acpid unzip curl tcpdump ca-certificates; 

apt-get clean -y;
apt-get autoclean -y;
apt-get autoremove -y;

cd /root
git clone https://github.com/Cynesiz/linux-configs
cd /root/linux-configs

chmod -R +x /root/linux-configs/httpd
cp /root/linux-configs/httpd/a2restart /usr/local/bin/
cp /root/linux-configs/httpd/savage /usr/local/bin/
cp /root/linux-configs/httpd/ngxrestart /usr/local/bin/

chmod -R 0750 /sbin
chmod -R 0750 /usr/sbin
chmod -R 0750 /usr/bin

reboot
