#!/bin/bash
# This one is okay :)
# chmod +x a2restart && sudo cp a2restart /usr/local/bin/

printf "%b" "\n\e[30;48;5;82m Restarting Apache \e[0m \n"
echo -e "\n\e[40;38;5;82m Stopping service... \e[0m \n"
service apache2 stop
echo -e "\n\e[40;38;5;82m Starting service... \e[0m \n"
service apache2 start
echo -e "\n\e[40;38;5;82m Checking status... \e[0m \n"
service apache2 status
echo -e "\n\e[40;38;5;82m Processes: \e[0m \n"
ps aux | grep apache
